# Generated by Django 4.1.1 on 2022-10-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
    ]
