# Generated by Django 4.1.1 on 2022-10-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
