# Generated by Django 4.1.1 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('hobby', 'Hobby'), ('sport', 'Sport'), ('animals', 'Animals'), ('vacantions', 'Vacantions'), ('vehicles', 'Vehicles'), ('clothes', 'Clothes'), ('tools', 'Tools'), ('real estate', 'Real Estate'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
