# Generated by Django 4.0 on 2022-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
