# Generated by Django 4.0 on 2022-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
