# Generated by Django 4.0 on 2022-11-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0003_alter_chatmessage_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiever', to='auth.user')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user')),
            ],
        ),
    ]
