# Generated by Django 4.0 on 2022-11-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_receiever_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
